
version: 2

models:
  - name: trips_clean
    description: "Data cleaning. 
    Input: dataset of ride sharing trips in NY. Each record corresponds to one trip, with information such as pickup location and time, ride distance, fares,... 
    Steps performed: remove records with negative fares (base_passenger_fare or driver_pay), rename trip_time to trip_time_in_s"
#    columns:
#      - name: id
#        description: "The primary key for this table"
#        data_tests:
#          - unique
#          - not_null

  - name: trips_per_week
    description: "Aggregation to average number of trips per week."

  - name: top_pickup_locations
    description: "Aggregation to trip count per pickup location zone, selection of top 5."

  - name: trip_length_time_by_hour_of_day
    description: "Aggregation to average trip distance and trip time per hour of the day."

